### ISSUE TITLE
[BUG] Getting "duplicate key" exception when installing Forge 1.20.1

### ISSUE THREAD

**Issue by ItsTheSky** [CmlLib/CmlLib.Core.Installer.Forge#3]
Hi there, I'm getting the following exception when trying to install forge 1.20.1 with version `47.2.32`:
```
An item with the same key has already been added. Key: Name
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at CmlLib.Utils.JarFile.GetManifest()
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.startProcessor(JToken processor, Dictionary`2 mapData)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.StartProcessors(JArray processors, Dictionary`2 mapData)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.MapAndStartProcessors(JObject installProfile, String installerDir)
   at CmlLib.Core.Installer.Forge.Installers.FNewest.Install(String installerDir)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.Install(ForgeInstallOptions options)
   at CmlLib.Core.Installer.Forge.MForge.Install(ForgeVersion forgeVersion, ForgeInstallOptions options, Boolean forceUpdate)
   at CmlLib.Core.Installer.Forge.MForge.Install(String mcVersion, String forgeVersion, ForgeInstallOptions options, Boolean forceUpdate)
```

Any idea what did I do wrong?

**Comment by AlphaBs** [comment]
I fixed this on 0.0.2. what version do you use?

**Comment by ItsTheSky** [comment]
Oh, well I am indeed using 0.0.2

**Comment by AlphaBs** [comment]
sorry it was 0.0.3.

**Comment by ItsTheSky** [comment]
Oops my bad, I forgot I fixed this issue by using another sub-version of fabric in 1.20.1. Sorry for any inconvenience!
